# 添付のSNSトピックを作成するCloudFormationテンプレートを改造して、トピック作成とともに、配信ステータスのログ記録の有効化するようにしてください。
# AWSコンソール上で、以下のようになっていればOKです。
# なお、配信ステータスのログ記録の有効化はCloudFomationではサポートされていないため、CloudFormationでカスタムリソースを作成して、SDKで有効化する必要があります。
 

 
 AWSTemplateFormatVersion: 2010-09-09

Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Join:
          - "-"
          - - test-topic
            - Fn::Select:
                - 4
                - Fn::Split:
                    - "-"
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - /
                            - Ref: AWS::StackId

Outputs:
  TopicArn:
    Value: !Ref Topic
